# This Pipeline helps with updating modules because dependabot was not cooperating with me

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get dist-upgrade
  displayName: 'update ubuntu packages'
  
- script: |
    git init
    git tag
    git submodule init
    git submodule update
  displayName: 'update modules'

- script: |
    sudo apt install wine-stable
    wine cmd < powershell < Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    wine cmd < choco install rustup.install
    wine cmd < cargo install rojo
    wine cmd < build.bat
