# This Pipeline helps with updating modules because dependabot was not cooperating with me

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get dist-upgrade
  displayName: 'update ubuntu packages'
  
- script: |
    git config --global user.email "hopejwest32@gmail.com"
    git config --global user.name "Hoidberg"
    git init
    git tag
    git submodule init
    git submodule update
    git diff --output=diff.txt
    git commit -a
  displayName: 'update modules'
