# This Pipeline helps with updating modules because dependabot was not cooperating with me

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get dist-upgrade
  displayName: 'update ubuntu packages'
  
- script: |
    git init
    git tag
    git submodule init
    git submodule update
  displayName: 'update modules'

- script: |
    sudo dpkg --add-architecture i386 
    wget -nc https://dl.winehq.org/wine-builds/winehq.key
    sudo apt-key add winehq.key
    sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
    sudo apt update
    sudo apt install --install-recommends winehq-stable
    winehq build.bat