# This Pipeline helps with updating modules because dependabot was not cooperating with me

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'
  
- bash: |
    kubeadm init
  displayName: "initialize kubeadm"