site_name: Roact Documentation
site_url: https://roblox.github.io/roact/
repo_name: Roblox/roact
repo_url: https://github.com/polycue/rbxlua-api/

theme:
  name: material
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
