site_name: RBXLua API for Polycue
site_url: https://polycue.github.io/rbxlua-api/
repo_name: polycue/rbxlua-api
repo_url: https://github.com/polycue/rbxlua-api/

theme:
  name: material
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Guide:
    - Installation: 

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
